# Local configuration
# Location of SAMTools
SAMTOOLS=/home/vagrant/tools/samtools

# Number of threads for functional tests, set to 2 or more, recommended to match number of cores
THREADS=2

# Acceptance test tuning variables (seconds), set to realistic values for your system
# Numbers based on running in CI on Intel i7 2.8GHz, 8 cores, 24GB RAM
COLOUSINGBD15_TIME=60
COLOWOBD15_TIME=80
SIM1CHRVS20305_TIME=60
